import { v4 as uuid } from "uuid";

export const customers = [
  {
    id: uuid(),
    address: {
      country: "Tunisia",
      state: "Tunisia",
      city: "Sfax",
      street: "route tunis",
    },
    // avatarUrl: "/static/images/avatars/avatar_3.png",
    createdAt: 1555016400000,
    email: "Mongi123@gmail.com",
    name: "Mongi Charfi",
    phone: "96984640",
  },
  {
    id: uuid(),
    address: {
      country: "Tunisia",
      state: "Tunisia",
      city: "Sfax",
      street: "route Lafrane",
    },
    // avatarUrl: "/static/images/avatars/avatar_4.png",
    createdAt: 1555016400000,
    email: "mohamed@gmail.com",
    name: "Mohamed Ellouze",
    phone: "97936555",
  },
  {
    id: uuid(),
    address: {
      country: "Tunisia",
      state: "Tunisia",
      city: "Sfax",
      street: "route Mahdia",
    },
    // avatarUrl: "/static/images/avatars/avatar_2.png",
    createdAt: 1555016400000,
    email: "Bilelderbel@yahoo.com",
    name: "Bilel Derbel",
    phone: "26897612",
  },
  {
    id: uuid(),
    address: {
      country: "Tunisia",
      state: "Sousse",
      city: "Chat Mariem",
      street: "route Mahdia",
    },
    // avatarUrl: "/static/images/avatars/avatar_5.png",
    createdAt: 1554930000000,
    email: "Hamdifarhat@gmail.com",
    name: "Hamdi Farhat",
    phone: "90869142",
  },
  {
    id: uuid(),
    address: {
      country: "Tunisia",
      state: "sousse",
      city: "boujaafer",
      street: "boujaafer",
    },
    // avatarUrl: "/static/images/avatars/avatar_6.png",
    createdAt: 1554757200000,
    email: "Amiramara@yahoo.com",
    name: "Amir Amara",
    phone: "97233300",
  },
  {
    id: uuid(),
    address: {
      country: "USA",
      state: "California",
      city: "Bakerfield",
      street: "317 Angus Road",
    },
    avatarUrl: "/static/images/avatars/avatar_1.png",
    createdAt: 1554670800000,
    email: "adam.denisov@devias.io",
    name: "Adam Denisov",
    phone: "858-602-3409",
  },
  {
    id: uuid(),
    address: {
      country: "USA",
      state: "California",
      city: "Redondo Beach",
      street: "2188  Armbrester Drive",
    },
    avatarUrl: "/static/images/avatars/avatar_7.png",
    createdAt: 1554325200000,
    email: "ava.gregoraci@devias.io",
    name: "Ava Gregoraci",
    phone: "415-907-2647",
  },
  {
    id: uuid(),
    address: {
      country: "USA",
      state: "Nevada",
      city: "Las Vegas",
      street: "1798  Hickory Ridge Drive",
    },
    avatarUrl: "/static/images/avatars/avatar_8.png",
    createdAt: 1523048400000,
    email: "emilee.simchenko@devias.io",
    name: "Emilee Simchenko",
    phone: "702-661-1654",
  },
  {
    id: uuid(),
    address: {
      country: "USA",
      state: "Michigan",
      city: "Detroit",
      street: "3934  Wildrose Lane",
    },
    avatarUrl: "/static/images/avatars/avatar_9.png",
    createdAt: 1554702800000,
    email: "kwak.seong.min@devias.io",
    name: "Kwak Seong-Min",
    phone: "313-812-8947",
  },
  {
    id: uuid(),
    address: {
      country: "USA",
      state: "Utah",
      city: "Salt Lake City",
      street: "368 Lamberts Branch Road",
    },
    avatarUrl: "/static/images/avatars/avatar_10.png",
    createdAt: 1522702800000,
    email: "merrile.burgett@devias.io",
    name: "Merrile Burgett",
    phone: "801-301-7894",
  },
];
